export const JafToken = 'jaf-jwt'
export const BaseApiUrl = 'https://jdkru13pp5.execute-api.ap-southeast-2.amazonaws.com/v1/'
export const BaseSpotifyApiUrl = 'https://accounts.spotify.com/'
export const SpotifyClientId = '678f8fa942f640deaad0fa4f8005c98d'
export const SpotifyScopes = 'user-read-private user-read-email'